### ISSUE TITLE
Unifying the build system

### ISSUE THREAD

**Issue by menuet** [thomsonreuters/Elektron-SDK#13]
Hi,
Did you think about using a cross-platform build system like cmake or gyp ?
If you think it is valuable, I am willing to help and begin a poc on a branch.

**Comment by menuet** [comment]
As a proof of concept, I forked the repository to https://github.com/menuet/Elektron-SDK and I created a branch cmake where I added 4 files CMakeLists.txt which are the rough equivalents (many details missing or changed) of all the files vcxproj and sln that are currently in Eta and Ema.

**Comment by GregLee-TR** [comment]
We have been talking about options like these as it could be very beneficial for both clients and development.  I really appreciate the POC and any insight that it brings.

**Comment by menuet** [comment]
If you are interested I can continue working on the POC. I can tweak the files CMakeLists.txt so that they can build ETA+EMA for the following platforms:
- Windows + VS2013 + x64 (and x86)
- Windows + VS2015 + x64 (and x86)
- CentOS 7 + gcc 4.8 + x64
- Ubuntu 14.04 + gcc 4.8 + x64
Once this is done, I can propose a pull request to your Preview branch.
What do you think ?

Note : when I say "done", I mean only that the binaries for Eta and Ema can be built, not that they are fullly usable and equivalent to the ones created with makefiles and vcxproj.

**Comment by GregLee-TR** [comment]
Menuet, I talked with the team and we would be appreciative of any further work on your POC. As I mentioned we have been thinking about other options (gradle or gyp) as well, but input from the open source community would be great!    Keep us posted on your efforts and we can peek at your fork for insight on cmake usage.

Thanks again!

**Comment by addicticks-dev** [comment]
I don't think the build system necessarily needs to be the same between C++ and Java parts. Java devs don't want to build the C++ parts, and vice versa.  (in fact they typically can't because they don't have the required tool chain to build the other part). I would definitely vote against such unification of build system. Mainly because I'm not aware of any such system that would be instantly familiar to both camps of developers.

The most important thing is that the build system is familiar to the target group (being it C++ devs or Java devs) and that they can instantly make use of the open source code in their IDE. The current status in the Java area of the SDK is a far cry from this, with the Ant-based build system giving me associations to mid 90'ties (sorry, it's true). Something needs to happen for the SDK to get the exposure it deserves. Right now it really feels like an odd fish to a Java developer. I've created [a POC](https://github.com/thomsonreuters/Elektron-SDK/issues/21) for how to improve on the situation for the Java parts of the SDK. It is based on Maven and whether you like Maven or not, you gotta recognize that 80% of open source Java projects out there are Maven-based. 

Another thought for TR: Have you considered to split the C++ and Java parts in two different repos ?  How do they benefit, currently, from being in the same repo? Not much. I appreciate the affinity that you, TR, need to keep between the C++ and Java versions, but that is of no concern to the devs you want to attract as contributors. They don't care about that.  They will always be either C++ dev or Java dev, not both at the same time.

Also, in Java world, we normally say that the litmus test if things should be in the same repo or not is if they follow the same release cycle.  Is the intention that the C++ and Java part should always follow the same release cycle? Do you really want to re-release the C++ lib just because a change was needed in the Java part?  (or vice versa). I'm not saying that you cannot have things in same repo and then use a different release cycle for the different parts within the repo, I just haven't seen it done with any success.

In essence I vote to split the repo. Then the C++ part and the Java part can implement what is most natural to their target group. 

I hope this was food for thought.

/Lars

**Comment by IainScott** [comment]
Thanks Lars this is really useful input.

Our goal is certainly to keep feature parity between API languages and there are scenarios where developers use both language versions within their environments.  That said, I can certainly understand your point around the benefits of separation.

The team here will review (on this and the other comments around build) and we'll get back to you asap.

Thanks

Iain

**Comment by addicticks-dev** [comment]
Two comments: 

Feature parity between C++ and Java versions (and I salute that aim), doesn't imply that they should follow the same release schedule.

> there are scenarios where developers use both language versions within their environments.

Really? I would think that any project within a given organization will decide to use **either** the C++ or the Java version, not both at the same time. Sure, in some large organizations you will see both in use in different parts of the org, but never within the same project and thus same people. I sometimes transcend C++ and Java, but in the bigger scheme of things this is very, very rare. And even for myself, who understands both worlds, it is much more important that the C++ part walks and talks like a typical C++ Open Source project and the same for the Java part, than the fact that the two live together.

Just my two cents. I've made my point.  :-)

/Lars

**Comment by BrianSandri** [comment]
Lars, 
We see enough customers that want that parity at the same time that I am inclined to try and keep that going.  In addition, within the team, we try to have the developers cross over the language so we can ensure consistency with not only when but also how the changes are made.  In the past, we had issues where things would be fixed in C++ but then never make it into Java (as well as the opposite).  By having the team work on things at the same time, we have been more successful in keeping the API consistent and the timing has been key in that.
