### ISSUE TITLE
EMA issue with Reactor Channel

### ISSUE THREAD

**Issue by TD-BNP** [thomsonreuters/Elektron-SDK#41]
Hello,
I am facing an issue while making snapshot with EMA through an ads server. The issue is linked to the number of products I send to the ads (around 75,000). When reaching around 30,000 the ReactorChannel becomes DOWN and so my application doesn't send anything anymore to the ads. The problem is all the remaining products are stored in the unsent queue and the number of WorkerEvent incredibly increases (more than 10 millions instances whereas I have only 75,000 products I am requesting with two fields for each).
Do you have any idea why this is happening? Is there any limit somewhere regarding the number of requests to send through a ReactorChannel?
Thanks in advance.

**Comment by frajt** [comment]
Hi,

could you provide jstack of the process before and after the ReactorChannel goes DOWN? 

Regards,
Michal

**Comment by TD-BNP** [comment]
Hello Michal,
What do you mean by jstack before and after? Indeed I dont have any error (no error stack) but when I am in Debug mode, I notice after 30,000 products the method WlStream.isChannelUp always returns false because the _state of the ReactorChannel is DOWN and so my unsent msg are stored in the _unsentMsgQueue.

**Comment by TD-BNP** [comment]
I have forgotten to precise I met an ErrorInfo "Channel out of buffers" before the channel becoming DOWN. But I havent found what it means yet.

**Comment by frajt** [comment]
Just run the jstack command with the process id of your Java application.
jstack <pid> >beforedown.txt
jstack <pid> >afterdown.txt

**Comment by frajt** [comment]
"Channel out of buffers", your app might be running out of memory, not reading fast enough the snapshot responses from the ADS. Please check your GC setting. Take care that you don't block too much in the OmmConsumerClient onRefreshMsg/onStatusMsg methods. If you need to print or call a database operation you will have to do it over a queue in another thread. If you block the processing you will get disconnected due to the "Channel out of buffers". Optionally you could request your 75,000 items in blocks.

**Comment by TD-BNP** [comment]
for the jstack it will be complicated: I'm posting from my mobile as where I work the source code is confidential and we are not allowed to visit github. So its complicated to post the jstack result.
But thanks to your answer regarding the ErrorInfo, I am looking at this way following your advise.

**Comment by TD-BNP** [comment]
Before the migration of our app to EMA we never met any memory or performance issue while we were using RFA. During the migration, I havent changed anything in our app, just the realtime protocol has changed. That is why I didnt suspect any bad behavior in our app. But from what I have understood, the behavior of EMA is not similar to RFA?

**Comment by frajt** [comment]
The EMA design took huge simplification in the threading model compare to the RFA. There is a primitive global lock around all consumer activities (request/submit/process channel) without any queueing option. All more or less runs single threaded. More you request, more you get back, more contention at global lock, less reading from ADS channel, more queuing at the ADS side leading to disconnection due to "Channel out of buffers". 
I don't think your app will ever work with the EMA. The EMA is way to simplified with plenty of implementation bugs. The simplification went too far to be usable for real production applications. It acts as marketing API where the connection and retrieval fits to a single source code page. I am very much convinced it cannot replace RFA any time soon. And I know what the Reuters APIs were all about (2001> SSL Classic C, SFC, RFA, UPA, EMA, C++/Java/.Net, both consumers and providers).

**Comment by zfarberov** [comment]
Likely output buffers for the channel, but can be input.  Please see “Universal Channel Entry Parameters” in developer guide for
More details on sizing.

Would look at emaConfig at channel definition to tune,
Would try increasing GuaranteedOutputBuffer sizing, the default may not be sufficient for your request requirements.

Totally agree with Michal, requesting in blocks is a good approach, as it should control use of the buffers, both out and in.

**Comment by TD-BNP** [comment]
Hello zfarberov,

You were right the solution was in the config.xml. I forgot to add the line to define the number of guarantedOutputBuffers. So by default this number is set to 100 which is incredibly low for my usage (around 80 000 products).
So I have increased it to 5,000 and it now works perfectly. No more memory issues that were caused by not enough buffers, so too many WorkerEvent created (around 10 millions) to store all the unsent msg.

And regarding the requests by blocks, it was already the case in my app: I request by blocks of 10,000 products.

**Comment by TD-BNP** [comment]
The only bad concept for me in EMA is the bad behavior of the app in degraded mode (when the config is not optimized): there are no limits in the VaQueue avoiding memory issues.

**Comment by bberner** [comment]
Changing an existing application from RFA to EMA by just dropping in EMA may not always be the best approach. Reviewing the EMA examples and looking at the Developer Community (link below) documentation and tutorials is always helpful when encountering these types of issues.

https://developers.thomsonreuters.com/elektron/elektron-sdk-java

The EMA Java performance example (emajconsperf) is similar to your program in that it requests a large number of items. It uses a GuaranteedOutputBuffer setting of 50000 to accommodate the large number of item requests.

**Comment by TD-BNP** [comment]
Hello @bberner,
I have documented before dropping from RFA to EMA. But my error was just I forget one property in my config file (wrong copy paste ^^).
And now my app works very fine, I had already implemented the other specifities of EMA besides RFA.
But I never heard about emajconsperf. Where can I find it? Its not in the Reuters examples (even the highest levels).

**Comment by seba5** [comment]
Hi, 

We are glad to hear that you have your application working. The example mentioned above can be found here: 

https://github.com/thomsonreuters/Elektron-SDK/tree/master/Java/Ema/Src/perftools
